# Generated by Django 5.2.9 on 2025-12-03 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Le contenu de la citation', verbose_name='Texte de la citation')),
                ('author', models.CharField(help_text="Nom de l'auteur de la citation", max_length=200, verbose_name='Auteur')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-created_at'],
            },
        ),
    ]
